# Generated by Django 3.2.16 on 2025-12-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_comment_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(help_text='Если выбрать дату и время в будущем, то публикация будет отложенной.', verbose_name='Дата и время публикации'),
        ),
    ]
